name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or master

permissions:
  contents: read
  packages: write  # Needed to publish Docker images to GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (optional)
      - name: Run tests
        run: npm test || echo "No tests defined"

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/backend-sequelize:latest
          echo "Building image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .

      # Log in to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/backend-sequelize:latest
          echo "Pushing image: $IMAGE_NAME"
          docker push $IMAGE_NAME
